# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1taPMjFzYSoEf72MSs3kOHS3datfaP5FD
"""

import pandas as pd
baza={
    "FISH":["Qadamova Zulayho","Xalilov Durbek","Joʻrayeva Gulnoza","Arabboyev Alisher","Turdimatov Maʼmurjon" ],
    "Fan nomi":["Sunʼiy intellekt","Sunʼiy intellekt","Elektronika va sxemalar ","Kiberxavfsizlik asoslari","Kiberxavfsizlik asoslari"],
    "Mashgʻulot turi":["amaliy","maʼruza","amaliy","amaliy","ma'ruza"],
    "Kafedrasi":["Axborot texnologiyalari ","Axborot texnologiyalari ","Tabiiy fanlar","Axborot texnologiyalari","KISIF"]
}
db=pd.DataFrame(baza)
print(db)

db.to_excel("teachers.xlsx")